dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - ffmpeg
env:
  global:
    - KLANGBECKEN_DATA=/tmp/data
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - pre-commit run -a
  - klangbecken init -d $KLANGBECKEN_DATA
  - coverage run --source=klangbecken -m unittest discover
  - flake8
after_success:
  - codecov
matrix:
  include:
    - language: minimal
      services:
        - docker
      addons:
        apt:
          packages:
      before_install:
      install:
      script:
        - docker run --rm -ti radiorabe/liquidsoap --version
        - mkdir $KLANGBECKEN_DATA
        - touch $KLANGBECKEN_DATA/prio.m3u $KLANGBECKEN_DATA/music.m3u $KLANGBECKEN_DATA/classics.m3u $KLANGBECKEN_DATA/jingles.m3u
        - docker run --rm -ti -e KLANGBECKEN_DATA=$KLANGBECKEN_DATA -v $KLANGBECKEN_DATA:$KLANGBECKEN_DATA -v `pwd`:/var/lib/liquidsoap radiorabe/liquidsoap --check klangbecken.liq
      after_success:
