language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install tox-travis
  - pip install mutagen werkzeug coveralls
script:
  - cd backend
  - tox
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coverage run --source=klangbecken_api -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coverage report -m; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
