language: python
python:
  - 3.6

# note: python3.5 is not preinstalled on docker-based (i.e. sudo: false)
#       Travis workers at the moment of this writing, so we need to get
#       it via addon repository.
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3.5-dev
      - liquidsoap
      - liquidsoap-plugin-icecast

install:
  - pip install tox
  - pip install mutagen werkzeug coveralls

script:
  - tox
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report -m
  - liquidsoap --version
  - test -f klangbecken.liq && liquidsoap --check klangbecken.liq

after_success:
  - coveralls
