language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install tox-travis
  - pip install coveralls
script:
- cd backend && if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coverage run -m tox; else tox; fi
after_success:
  if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi
