dist: trusty
sudo: false
language: python
python: 3.6

addons:
  apt:
    packages:
      - liquidsoap
      - liquidsoap-plugin-icecast
      - liquidsoap-plugin-lame
env:
  global:
    - KLANGBECKEN_DATA=data

install:
  - pip install tox
  - pip install mutagen werkzeug coveralls

script:
  - tox
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report -m
  - liquidsoap --version
  - test -d $KLANGBECKEN_DATA || mkdir $KLANGBECKEN_DATA
  - test -f klangbecken.liq && liquidsoap --check klangbecken.liq

after_success:
  - coveralls
