dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - liquidsoap
      - liquidsoap-plugin-icecast
      - liquidsoap-plugin-lame
      - liquidsoap-plugin-alsa
      - ffmpeg
env:
  global:
    - KLANGBECKEN_DATA=/tmp/data

install:
  - pip install tox
  - pip install .
  - pip install coverage
  - pip install codecov

script:
  - tox
  - liquidsoap --version
  - test -d $KLANGBECKEN_DATA || mkdir $KLANGBECKEN_DATA
  - touch $KLANGBECKEN_DATA/prio.m3u
  - test -f klangbecken.liq && liquidsoap --check klangbecken.liq
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report --fail-under=90 -m

after_success:
  - codecov
