dist: trusty
sudo: false
language: python
python: 3.6

addons:
  apt:
    packages:
      - liquidsoap
      - liquidsoap-plugin-icecast
      - liquidsoap-plugin-lame
      - liquidsoap-plugin-alsa
env:
  global:
    - KLANGBECKEN_DATA=data
    - KLANGBECKEN_API_SECRET=deadbeef

install:
  - pip install tox
  - pip install .
  - pip install coverage coveralls

script:
  - tox
  - liquidsoap --version
  - test -d $KLANGBECKEN_DATA || mkdir $KLANGBECKEN_DATA
  - test -f klangbecken.liq && liquidsoap --check klangbecken.liq
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report -m
  - coveralls
