language: python
python:
  - 3.6
install:
  - pip install tox
  - pip install mutagen werkzeug coveralls
script:
  - tox
  - coverage run --source=klangbecken_api -m unittest discover
  - coverage report -m
after_success:
  - coveralls
